# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# Disable configuration cache due to serialization issues
org.gradle.configuration-cache=false

# Kotlin
kotlin.code.style=official

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=true
android.nonFinalResIds=true
android.suppressUnsupportedCompileSdk=35

# Disable build features by default (overridden per module)
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderScript=false
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false
