package com.parentalcare.core.security.pairing

import android.content.Context
import android.content.SharedPreferences
import com.parentalcare.core.common.util.SecureTokenGenerator
import kotlin.text.Charsets
import java.security.MessageDigest
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Screenshot request integrity token.
 *
 * - Prevents replay attacks: child rejects any request whose nonce it has
 *   already seen.
 * - Prevents forged requests: only parent-signed requests are honored. The
 *   signature is generated by a Cloud Function using the parent's server
 *   identity (this is server-side, see Firebase rules + functions/).
 *
 * This class is the on-device counterpart — it verifies the request matches
 * the expected shape (nonce freshness, familyId matches device's bound
 * familyId, expiration in the future).
 */
data class ScreenshotRequest(
    val requestId: String,
    val familyId: String,
    val parentUserId: String,
    val childDeviceId: String,
    val createdAt: Long,
    val expiresAt: Long,
    val nonce: String,
    val status: String,
) {
    val isExpired: Boolean get() = System.currentTimeMillis() > expiresAt
}

object ScreenshotRequestValidator {

    /**
     * Returns true iff the request is fresh, unexpired, and addressed to
     * the given device.
     */
    fun isValid(
        request: ScreenshotRequest,
        expectedFamilyId: String,
        expectedDeviceId: String,
        now: Long = System.currentTimeMillis(),
    ): Boolean {
        if (request.familyId != expectedFamilyId) return false
        if (request.childDeviceId != expectedDeviceId) return false
        if (now > request.expiresAt) return false
        if (request.createdAt > now + CLOCK_SKEW_MS) return false // future-dated
        if (request.nonce.length < 16) return false // weak nonce
        return true
    }

    private const val CLOCK_SKEW_MS = 30_000L // 30s tolerance
}

/**
 * Persistent nonce registry using EncryptedSharedPreferences.
 * Survives app restarts to prevent replay attacks.
 */
@Singleton
class NonceRegistry @Inject constructor(
    @dagger.hilt.android.qualifiers.ApplicationContext private val context: Context,
) {

    private val prefsName = "nonce_registry"
    private val NONCE_TTL_MS = 60L * 60 * 1000 // 1 hour
    private val MAX_NONCES = 1024

    private val prefs: SharedPreferences by lazy {
        val masterKey = androidx.security.crypto.MasterKey.Builder(context)
            .setUserAuthenticationRequired(false)
            .setKeyScheme(androidx.security.crypto.MasterKey.KeyScheme.AES256_GCM)
            .build()
        androidx.security.crypto.EncryptedSharedPreferences.create(
            context,
            prefsName,
            masterKey,
            androidx.security.crypto.EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
            androidx.security.crypto.EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM,
        )
    }

    fun isFresh(nonce: String, now: Long = System.currentTimeMillis()): Boolean {
        val seenAt = prefs.getLong(nonce, -1L)
        if (seenAt != -1L && now - seenAt < NONCE_TTL_MS) return false
        
        // Clean up expired entries before adding new one
        cleanupExpired(now)
        
        prefs.edit().putLong(nonce, now).apply()
        return true
    }

    private fun cleanupExpired(now: Long) {
        val editor = prefs.edit()
        var count = 0
        val toRemove = mutableListOf<String>()
        
        for ((key, value) in prefs.all) {
            if (value is Long) {
                if (now - value >= NONCE_TTL_MS) {
                    toRemove.add(key)
                } else {
                    count++
                }
            }
        }
        
        // If still over capacity, remove oldest entries
        if (count >= MAX_NONCES) {
            val sortedEntries = prefs.all.entries
                .filter { it.value is Long }
                .sortedBy { (it.value as Long) }
                .take(count - MAX_NONCES + 1)
                .map { it.key }
            toRemove.addAll(sortedEntries)
        }
        
        toRemove.forEach { editor.remove(it) }
        editor.apply()
    }
}

/** Generates a fresh request nonce for tests / parent app signing. */
fun freshNonce(): String = SecureTokenGenerator.generateNonce()

/** SHA-256 hex of input — used for digest lookups. */
fun sha256Hex(input: String): String {
    val md = MessageDigest.getInstance("SHA-256")
    return md.digest(input.toByteArray(Charsets.UTF_8))
        .joinToString("") { "%02x".format(it) }
}
